// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntrivhnvoktbgyskfhfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50cml2aG52b2t0Ymd5c2tmaGZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMzI2NjYsImV4cCI6MjA2MTcwODY2Nn0.PpIQ_PIS-CwoVzrFTdP1d8xoxrcNmP9mRm0JJzvRzsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);